### ISSUE TITLE
live reload does not appear to work

### ISSUE THREAD

**Issue by MarkHerhold** [tthew/gulp-angular-webpack-seed#4]
It seems like there are live-reload capabilities with `webpack-dev-server` and I don't see them actually working.

**Comment by rafael-ochoa** [comment]
Hi MarkHerhold,
Have you tried adding this line to your index,html?

````html
  <script src="http://localhost:5000/webpack-dev-server.js"></script>
.....
    {% for (var chunk in o.htmlWebpackPlugin.assets) { %}
    <script src="{%=o.htmlWebpackPlugin.assets[chunk]%}"></script>
    {% } %}
````

**Comment by MarkHerhold** [comment]
I don't believe I did when I tried it. I only tried this seed and moved on when I found live reload wasn't working.
